### ISSUE TITLE
Change CSS to account for scrollbars on desktop

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#59]
Currently, when using the "Cover" view, the scrollbars interfere with the game tiles, at least on Chrome. But if you make space for them in CSS, it can look a bit neater.

BEFORE: https://i.imgur.com/vPa9cch.png
AFTER: https://i.imgur.com/hMYLvaA.png 

Your code: 
```css
.list .games[data-v-41e546bc] {
padding: 0 8px;
}
```

My code:
```css
.list .games[data-v-41e546bc] {
padding: 0px 20px 0px 5px;,
}
```

UPDATE: Fixed the code highlighting
