### ISSUE TITLE
Horizontal scrolling bar broken on Chrome

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#60]
Currently can't use horizontal scroll bar on Chrome, it is unresponsive. I can still scroll using Shift+Scrollwheel, but this is a crutch. Touch scrolling on mobile works.

**Comment by areyouokani** [comment]
Found the reason - your footer is blocking it. As a hotfix, you can change padding to margin in order to make the scroll-bar interactable.

Your code:
```css
footer[data-v-65c29ea9] {
    padding: 8px 0;
}
```

My code:
```css
footer[data-v-65c29ea9] {
    margin: 8px 0;
}
```
