### ISSUE TITLE
Make the list backgrounds transparent

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#61]
Now that we have wallpapers, let's make them actually visible on busy gamebraries! How about toogleable 50% transparency for the list backgrounds?

CURRENT: 
![image](https://user-images.githubusercontent.com/29702693/56017738-e5eac280-5d08-11e9-8433-cbfa6aa1b2ee.png)

TRANSPARENT:
![image](https://user-images.githubusercontent.com/29702693/56017720-d4a1b600-5d08-11e9-9186-ac65398a52db.png)

CODE:
```css
.list[data-v-41e546bc] {
    background: rgba(255, 255, 255, 0.5);
}
```
