### ISSUE TITLE
Some visual updates for Cover Mode

### ISSUE THREAD

**Issue by areyouokani** [romancm/gamebrary#62]
Spent an hour hacking into GameBrary with Stylish, trying to make Cover Mode look better. Here's what I got so far: 

[GIFV](https://imgur.com/a/HEkJYPW) - Warning, 42 MB.

IDEAS:
CSS allows for customizable scroll bars, so let's make Gamebrary's slimmer and more modern. I'd also like to make them appear only when you hover over the list. Haven't figured out how it would work, though.
``` css
::-webkit-scrollbar {
  height: 5px;
  width: 5px;
}

::-webkit-scrollbar-thumb {
  background: #555;
}

::-webkit-scrollbar-thumb:hover {
  background: #333;
}
```
Paddings in the cover mode are kinda large. How about 5 px increments? 

``` css
.list .games[data-v-36ad86b3] {
  padding: 5px 5px 5px 5px;
}

.game-card[data-v-36ad86b3] {
  margin-top: 0px;
}

.list.covers .games[data-v-36ad86b3] {
  grid-gap: 1px;
}

.lists[data-v-e0c6d97a] {
  padding: 0 10px 0 10px;
  margin-right: 10px;
}
```

Cool iOS-like transparency. Requires "EXPERIMENTAL WEB FEATURES" flag in Chrome, but works on Safari out of the box. Ignored in other browsers.

``` css
.list[data-v-36ad86b3] {
  backdrop-filter: blur(5px) contrast(.8);
  -webkit-backdrop-filter: blur(5px) contrast(.8);
}
```

Cover view already has covers with titles, so let's remove separate titles! 
WARNING: This exact code removes titles in the "add game" dialogue. Use for demo purposes only :) 

``` css
.game-card .game-info a[data-v-4b93e6db] {
  display: none;
}
```

Let's move the "Move" icon to the left corner and increase the drag area. It will look better and make dragging cards easier. 

``` css
.game-card .game-drag-handle[data-v-4b93e6db] {
  left: 5px;
  bottom: 5px !important;
}
```

"Add game" button doesn't have to be that small, it can easily take the full width of the list. Also, let's animate it on hover.

``` css
button[data-v-36ad86b3] {
  padding: 0 48% 0 49%;
  /* Kinda hacky solution but it works and doesn't break the other buttons in the process. */
  border-radius: 0px;
  /* Allows it to sit flush with the list when highlighted. */
}

button[data-v-36ad86b3]:hover {
  background: rgba(255, 255, 255, 0.75);
}

.list small {
  /* IMO, you don't really need the text on the button. "+" works just as well and looks a bit more elegant. */
  display: none;
}
```
The settings button has incorrectly set height, which becomes noticeable when you highlight it. This is a small cosmetic fix.

``` css
button.small[data-v-36ad86b3] {
  min-height: 30px;
}
```
